language: php

sudo: false

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer install

script:
    - ./vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
